### ISSUE TITLE
Some question about the calculation of quaternion

### ISSUE THREAD

**Issue by henrycjh** [meshonline/kinect-openni-bvh-saver#11]

**Comment by henrycjh** [comment]
@meshonline 老师您好，感谢您提供的代码。
我在做由3D 关键点得到四元数信息时参考了您的代码，有一个地方不太理解，就是// inverse bind pose这一步的作用是什么呢？

**Comment by meshonline** [comment]
Inverse bind pose是为了获得相对变换的。

比如：父节点的矩阵 * 子节点的相对变换 = 子节点的矩阵，那么等式两边同时左乘父节点的矩阵的逆矩阵，
变为：父节点的矩阵的逆矩阵 * 父节点的矩阵 * 子节点的相对变换 = 父节点的矩阵的逆矩阵 * 子节点的矩阵，
由于前两项相乘的结果为单位矩阵，所以化简为：子节点的相对变换 = 父节点的矩阵的逆矩阵 * 子节点的矩阵。
